# Generated by Django 5.2.13 on 2026-05-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
